<a href="https://colab.research.google.com/github/DommiiUdomp/Dommii/blob/main/ImportData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
#download from zip
import zipfile
import io
import requests

In [27]:
# file URL
url = "https://databank.worldbank.org/data/download/hnp_stats_csv.zip"

# download zip
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))

# get file names
csvfiles = []
for file in z.namelist():
  #df = pd.read_csv(file)
  csvfiles.append(file)
print(csvfiles)

df_all = []
for csvfile in csvfiles:
  df = pd.read_csv(z.open(csvfile))
  df_all.append(df) 

df = pd.concat(df_all,ignore_index=True)
df.head()

['HNP_StatsData.csv', 'HNP_StatsCountry.csv', 'HNP_StatsSeries.csv', 'HNP_StatsCountry-Series.csv', 'HNP_StatsSeries-Time.csv', 'HNP_StatsFootNote.csv']

                  Country Name Country Code  ... Year Unnamed: 4
0  Africa Eastern and Southern          AFE  ...  NaN        NaN
1  Africa Eastern and Southern          AFE  ...  NaN        NaN
2  Africa Eastern and Southern          AFE  ...  NaN        NaN
3  Africa Eastern and Southern          AFE  ...  NaN        NaN
4  Africa Eastern and Southern          AFE  ...  NaN        NaN

[5 rows x 123 columns]

In [122]:
url_pop = 'https://en.wikipedia.org/wiki/Provinces_of_Thailand'
pop = pd.read_html(url_pop)
type(pop[2])

pandas.core.frame.DataFrame

In [123]:
df_pop = pd.DataFrame(pop[2])
df_pop.drop(columns=['Seal','Name(in Thai)', 'Namesake town/city', 'ISO[7]', 'FIPS'], inplace = True)
df_pop.head()

                                    Name  ...  HS[6]
0  Bangkok (special administrative area)  ...    BKK
1                          Amnat Charoen  ...    ACR
2                              Ang Thong  ...    ATG
3                              Bueng Kan  ...    BKN
4                                Buriram  ...    BRM

[5 rows x 5 columns]

In [131]:
url_air = 'https://www.iqair.com/profile/thailand-air-quality-and-noise-management-bureau'
air = pd.read_html(url_air)

In [132]:
df_air = pd.DataFrame(air[0])
df_air.drop(columns=['followers','Unnamed: 3'], inplace = True)
df_air.head()

                                            Stations  AQI
0  Along Rama IV Rd., Pathum Wan Pathum Wan, Thai...   80
1           Chulalongkorn Hospital Bangkok, Thailand   84
2         Ladphrao District Office Bangkok, Thailand   76
3           Khlong Chan, Bang Kapi Bangkok, Thailand   59
4         Dindaeng Road, Din Daeng Bangkok, Thailand  114

In [133]:
df_air.tail()

                                             Stations  AQI
45  The Government Public Relations Department Pha...   82
46               Map Ta Phut, Mueang Rayong, Thailand   72
47        Chokchai Police Station Lat Phrao, Thailand   88
48          Kasertsart University Chatuchak, Thailand   82
49                  Mae Pa, Mae Sot Mae Sot, Thailand  124

In [134]:
df_air['Stations'].str.split(',',expand=True)

                                                    0  ...          3
0                                   Along Rama IV Rd.  ...       None
1                      Chulalongkorn Hospital Bangkok  ...       None
2                    Ladphrao District Office Bangkok  ...       None
3                                         Khlong Chan  ...       None
4                                       Dindaeng Road  ...       None
5                                           Phayathai  ...   Thailand
6                                        Khlong Nueng  ...   Thailand
7                                           Bang Phut  ...   Thailand
8                                            Ban Suan  ...       None
9                                           Phlapphla  ...       None
10                                     Bang Sao Thong  ...       None
11                                          Pratuchai  ...       None
12                                  Tambon Nai Mueang  ...   Thailand
13                                             Om Noi  ...       None
14                                            Pak Nam  ...   Thailand
15                                        Songkhanong  ...       None
16                                           Si Racha  ...       None
17                                        Hiran Ruchi  ...   Thailand
18                      Meteorological Staions Mueang  ...       None
19                                     Tambon Phrabat  ...       None
20                                          City Hall  ...       None
21                                           Mahachai  ...       None
22                                        Thung Sukla  ...       None
23                                       Tambon Talat  ...       None
24                                          Samae Dam  ...   Thailand
25                                 Intharaphithak Rd.  ...   Thailand
26                                         Pak Phriao  ...       None
27                                   Tambon Tha Pradu  ...       None
28                                            Sriphum  ...       None
29                             Nai Mueang Subdistrict  ...       None
30                                       Tambon Wiang  ...       None
31                                          Na Mueang  ...       None
32                                            Si Phum  ...       None
33   Kanchanaburi Meteorological Station Kanchanaburi  ...       None
34                                        Pak Nam Pho  ...       None
35                                        Pluak Daeng  ...       None
36                                       Chang Phueak  ...       None
37                                          Huay Pong  ...       None
38                                   Tambon Noen Phra  ...       None
39                                            Na Chak  ...       None
40                                           Wang Yen  ...       None
41                                          Talat Yai  ...       None
42                                          Nai Wiang  ...       None
43                                            Hat Yai  ...       None
44                                        Na Phra Lan  ...       None
45  The Government Public Relations Department Pha...  ...       None
46                                        Map Ta Phut  ...       None
47                  Chokchai Police Station Lat Phrao  ...       None
48                    Kasertsart University Chatuchak  ...       None
49                                             Mae Pa  ...       None

[50 rows x 4 columns]